server:
  port: 8080

spring:
  application:
    name: be-90z
  servlet:
    multipart:
      max-file-size: 10MB # 개별 파일의 최대 크기
      max-request-size: 10MB # 전체 요청의 최대 크기
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    encoding: UTF-8

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /
    doc-expansion: none

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}